name: Automation
on:
  pull_request:
  push:
    branches: [ "main" ]
    paths: [ "**.tf", "CHANGELOG.md"]

permissions:
  pull-requests: write
  contents: write

jobs:

  update-readme:
    if: github.event_name == 'pull_request'
    name: Update README for changed modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
        with:
          working-dir: .
          git-push: "true"
          git-push-sign-off: "true"
          config-file: ".terraform-docs.yml"

  terraform:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    name: Terraform checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Terraform
        run: terraform fmt -check -recursive

  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: terraform
    steps:
      - uses: googleapis/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        with:
          token: ${{ secrets.MARVIN_PAT }}
          release-type: terraform-module
          # signoff: "Marvin <117985362+4t2-marvin@users.noreply.github.com>"
          # prerelease: true
